### ISSUE TITLE
The build is still broken

### ISSUE THREAD

**Issue by byron-hawkins** [mbrt/libb64#1]
base64.cc: In function ‘int main(int, char**)’:
    base64.cc:83:19: error: no matching function for call to ‘base64::encoder::encoder()’
       base64::encoder E;

Normally I prefer to clone things from github whenever there is a mirror--but in this case you have broken it! So I'll go get the original off wonky old sourceforge.

**Comment by mbrt** [comment]
This is because I only cared about porting libb64 build to CMake, and not the base64 executable.

**Comment by mbrt** [comment]
I also changed the interface because it didn't make much sense, so it's not exactly equivalent to the original one
